version: '2'
services:
  kiosk: 
    image: "merchantville/kiosk"
    container_name: kiosk
    build: .
    network_mode: "host"
    privileged: true
    mem_limit: "1g"
    environment:
      - "DISPLAY=$DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./assets/mozilla/firefox/avfatqu6.default/extensions.ini:/root/.mozilla/firefox/avfatqu6.default/extensions.ini"
      - "./assets/mozilla/firefox/profiles.ini:/root/.mozilla/firefox/profiles.ini"
