version: '2'
services:
  kiosk: 
    image: "merchantville/kiosk"
    build: .
    network_mode: "host"
    mem_limit: "512m"
    command: |
      --disable-overlay-scrollbar
      --incognito
      --no-default-browser-check
      --kiosk
      --user-data-dir=/data
      merchantvillenj.gov
    environment:
      - "DISPLAY=unix$DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME/downloads:/root/Downloads"
      - "$HOME/.config/google-chrome:/data"
