version: '2'
services:
  kiosk: 
    image: "merchantville/kiosk"
    build: .
    network_mode: "host"
    mem_limit: "1g"
    command: |
      --disable-overlay-scrollbar
      --incognito
      --no-default-browser-check
      --user-data-dir=/data
      merchantvillenj.gov
      #--kiosk
    environment:
      - "DISPLAY=unix$DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./assets/data/urls.txt:/data/urls.txt"
      - "./volumes/downloads:/root/Downloads"
      - "./volumes/google-chrome:/data"
      - "./volumes/logs:/var/log"
