version: '2'
services:
  kiosk: 
    image: "devurandom/firefox"
    #image: "merchantville/kiosk"
    #build: .
    network_mode: "host"
    privileged: true
    mem_limit: "1g"
    #command:
    environment:
      - "DISPLAY=$DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./assets/data/urls.txt:/data/urls.txt"
      - "./volumes/downloads:/root/Downloads"
      - "./volumes/google-chrome:/data"


#--volumes-from storage
#--env DISPLAY="${DISPLAY}"
#--volume /tmp/.X11-unix:/tmp/.X11-unix
#--env PULSE_SERVER=unix:/tmp/pulse-unix
#--volume /run/user/"${UID}"/pulse/native:/tmp/pulse-unix "${dri_devices[@]}" 
#devurandom/firefox
